# Jenkins JNLP slave with packer

FROM jenkinsci/jnlp-slave

ARG PACKER_VERSION=1.2.2

USER root

RUN wget https://releases.hashicorp.com/packer/${PACKER_VERSION}/packer_${PACKER_VERSION}_linux_amd64.zip -O packer.zip && \
    unzip packer.zip && mv packer /usr/bin && rm -f packer.zip

USER jenkins
